### ISSUE TITLE
In webargs 6, use_args will accept a single location

### ISSUE THREAD

**Issue by lafrech** [maximdanilchenko/aiohttp-apispec#75]
Hi.

Just a friendly heads up about this change coming in the next major webargs version.

https://github.com/marshmallow-code/webargs/pull/420

Do you foresee any issue with this?

**Comment by maximdanilchenko** [comment]
@lafrech, hi!

Thank you for this information!

I will try to make needed changes as soon as possible to make it compatible with webargs 6.

**Comment by rch9** [comment]
Hi. 

I have an issue using 'webargs==6.1.0' and validation_middleware.
It works with 'webargs==5.5.3'

python3.7/site-packages/aiohttp_apispec/middlewares.py", line 34, in validation_middleware
    schema["schema"], request, locations=schema["locations"]
TypeError: parse() got an unexpected keyword argument 'locations'

**Comment by lafrech** [comment]
This lib is not compatible with webargs 6 (yet ?).

https://github.com/maximdanilchenko/aiohttp-apispec/blob/98324c052f46b478b7fb94ebc6c9c70ae39cecb7/requirements.txt#L3

**Comment by maximdanilchenko** [comment]
@rch9 it would be great if you can take a look!

**Comment by yarula** [comment]
https://github.com/marshmallow-code/webargs/blob/25475ed158a45a9963f401edc71c9ac5256706f7/src/webargs/asyncparser.py#L30
